/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.7.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 20/01/07
 ***********************************************************************************************/

#ifndef ENVIRONMENTALSENSOR_INTERFACE_H
#define ENVIRONMENTALSENSOR_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/xlogging.h"
#include "azure_c_shared_utility/threadapi.h"

#include "digitaltwin_client_helper.h"
#include "digitaltwin_serializer.h"
#include "parson.h"
#include "../sensorbox_1_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum ENVIRONMENTALSENSOR_TELEMETRY_TAG
{
    Environmentalsensor_TEMPERATURE_TELEMETRY,
    Environmentalsensor_HUMIDITY_TELEMETRY
} ENVIRONMENTALSENSOR_TELEMETRY;

typedef enum ENVIRONMENTALSENSOR_READONLY_PROPERTY_TAG
{
    Environmentalsensor_INTERVAL_PROPERTY
} ENVIRONMENTALSENSOR_PROPERTY;

// DigitalTwin interface name from service perspective.
static const char EnvironmentalsensorInterfaceId[] = "urn:DotNETForDevices:EnvironmentalSensor:1";
static const char EnvironmentalsensorInterfaceInstanceName[] = "environmentalsensor";

// Telemetry names for this interface.

static const char EnvironmentalsensorInterface_TemperatureTelemetry[] = "temperature";

static const char EnvironmentalsensorInterface_HumidityTelemetry[] = "humidity";

// Property names for this interface.

#define EnvironmentalsensorInterface_IntervalProperty "interval"

// Command names for this interface

#define EnvironmentalsensorInterface_ToggleCommand "toggle"

// Methods
DIGITALTWIN_INTERFACE_CLIENT_HANDLE EnvironmentalsensorInterface_Create();

void EnvironmentalsensorInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle);

DIGITALTWIN_CLIENT_RESULT EnvironmentalsensorInterface_Telemetry_SendAll();

#ifdef __cplusplus
}
#endif

#endif  // ENVIRONMENTALSENSOR_INTERFACE_H
