/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.7.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 20/01/07
 *******************************************************************************************/

#include "sensorbox_1_impl.h"
#include "utilities/digitaltwin_serializer.h"
#include "utilities/deviceinfo_interface.h"
#include "utilities/environmentalsensor_interface.h"

#define Payload_Buffer_Size 256

void SendTelemetry_Succeeded_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on success.

    LogInfo("DigitalTwin successfully delivered telemetry message for component %s", interfaceName);
}

void SendTelemetry_Error_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on failure.

    LogInfo("DigitalTwin failed to deliver telemetry message for %s", interfaceName);
}

void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback reporting property on success.

    LogInfo("DigitalTwin successfully report writable property for %s::%s", interfaceName, propertyName);
}

void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback of reporting property on failure.

    LogInfo("DigitalTwin failed to report writable property for %s::%s", interfaceName, propertyName);
}

char* Deviceinfo_Property_GetManufacturer()
{
    // TODO: provide implementation here
    return "abc";
}

char* Deviceinfo_Property_GetModel()
{
    // TODO: provide implementation here
    return "abc";
}

char* Deviceinfo_Property_GetSwVersion()
{
    // TODO: provide implementation here
    return "abc";
}

char* Deviceinfo_Property_GetOsName()
{
    // TODO: provide implementation here
    return "abc";
}

char* Deviceinfo_Property_GetProcessorArchitecture()
{
    // TODO: provide implementation here
    return "abc";
}

char* Deviceinfo_Property_GetProcessorManufacturer()
{
    // TODO: provide implementation here
    return "abc";
}

long Deviceinfo_Property_GetTotalStorage()
{
    // TODO: provide implementation here
    return 0L;
}

long Deviceinfo_Property_GetTotalMemory()
{
    // TODO: provide implementation here
    return 0L;
}

double Environmentalsensor_Telemetry_ReadTemperature()
{
    // TODO: provide implementation here
    return 0.0;
}

double Environmentalsensor_Telemetry_ReadHumidity()
{
    // TODO: provide implementation here
    return 0.0;
}

bool Environmentalsensor_Property_IntervalCallback(int interval)
{
    // TODO: provide implementation here
    LogInfo("Interval property new value: %d", interval);
    return true;
}

DIGITALTWIN_COMMAND_RESULT Environmentalsensor_Command_Toggle(char** response, unsigned int* statusCode)
{
    // TODO: provide implementation here
    // You need to process the device command, and set the command response and statusCode correspondingly.
    // Finally, return DIGITALTWIN_COMMAND_OK if the command execution succeeded, or 'DIGITALTWIN_COMMAND_ERROR' on failure.

    char* responseData = "Execute toggle successfully";
    *response = (char*)calloc(strlen(responseData) + 1, sizeof(char));
    strncpy(*response, responseData, strlen(responseData));

    *statusCode = 200;
    LogInfo("Device executed 'toggle' command successfully");
    return DIGITALTWIN_COMMAND_OK;
}

