/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.7.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 20/01/04
 *******************************************************************************************/

#include "SensorboxModel_impl.h"
#include "utilities/digitaltwin_serializer.h"
#include "utilities/environmentalsensor_interface.h"
#include "utilities/deviceinfo_interface.h"

#define Payload_Buffer_Size 256

static bool ledOn = false;

void SendTelemetry_Succeeded_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on success.

    LogInfo("DigitalTwin successfully delivered telemetry message for component %s", interfaceName);
}

void SendTelemetry_Error_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on failure.

    LogInfo("DigitalTwin failed to deliver telemetry message for %s", interfaceName);
}

void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback reporting property on success.

    LogInfo("DigitalTwin successfully report writable property for %s::%s", interfaceName, propertyName);
}

void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback of reporting property on failure.

    LogInfo("DigitalTwin failed to report writable property for %s::%s", interfaceName, propertyName);
}

double EnvironmentalSensor_Telemetry_ReadTemperature()
{
    return getDevKitTemperatureValue(0);
}

double EnvironmentalSensor_Telemetry_ReadHumidity()
{
    return getDevKitHumidityValue();
}

bool EnvironmentalSensor_Property_IntervalCallback(int interval)
{
    pnp_device_set_interval_time(interval);
    LogInfo("Interval property new value: %d", interval);
    return true;
}

DIGITALTWIN_COMMAND_RESULT EnvironmentalSensor_Command_Toggle(char** response, unsigned int* statusCode)
{
    // You need to process the device command, and set the command response and statusCode correspondingly.
    // Finally, return DIGITALTWIN_COMMAND_OK if the command execution succeeded, or 'DIGITALTWIN_COMMAND_ERROR' on failure.
    ledOn = ! ledOn;

    if (ledOn) {
        turnOnUserLED();
    } else {
        turnOffUserLED();
    }

    char* responseData = "Execute toggle successfully";
    *response = (char*)calloc(strlen(responseData) + 1, sizeof(char));
    strncpy(*response, responseData, strlen(responseData));

    *statusCode = 200;
    LogInfo("Device executed 'toggle' command successfully");
    return DIGITALTWIN_COMMAND_OK;
}

char* DeviceInfo_Property_GetManufacturer()
{
    return "DotNETForDevices";
}

char* DeviceInfo_Property_GetModel()
{
    return "AZ3166";
}

char* DeviceInfo_Property_GetSwVersion()
{
    return "1.0.0";
}

char* DeviceInfo_Property_GetOsName()
{
    return "mbed";
}

char* DeviceInfo_Property_GetProcessorArchitecture()
{
    return "Cortex-M4";
}

char* DeviceInfo_Property_GetProcessorManufacturer()
{
    return "MXCHIP";
}

long DeviceInfo_Property_GetTotalStorage()
{
    return 3 * 1024 * 1024;
}

long DeviceInfo_Property_GetTotalMemory()
{
    return 256 * 1024;
}

